@startuml
	package DomainModel {
		package ユーザー集約 {
			object ユーザー {
				ユーザーID : userId
				名前 : userName
				メールアドレス : mailAddress
				アイコン : userIcon
			}
			object フォロワー {
				ユーザーID : userId
				名前 : userName
				アイコン : userIcon
			}
		}

		package 投稿集約 {
			object 投稿 {
				投稿ID : postId
				タイトル : postTitle
				説明 : postDetail
				カロリー : calories
				難易度 : difficulty
			}
			object いいね {
				ユーザーID : userId
			}
			object プロセス {
				説明 : processDetail
				画像 : processImage
			}
			object 材料 {
				材料名 : materialName
				量 : count
			}
		}

		package 通知集約 {
			object SMS {
				送信ID
				通知区分
				コンテンツ
				ステータス
			}

			object メール {
				送信ID
				通知区分
				コンテンツ
				ステータス
			}
		}
	}
	
	note left of 通知集約
		* 通知区分は現状ユーザー登録のみ
		* ステータスは「送信中(pending)・送信済み(succeeded)・送信失敗(failed)」
	end note

	note left of いいね
		* １投稿にユーザーIDが同様のいいねは二つ以上存在しない
		* 自分の投稿にはいいねできない
	end note

	note left of 投稿
		* 難易度は1~5段階
		* 説明は200文字以内
		* タイトルは40文字以内
		* 自分の投稿は編集・削除が出来る
	end note

	note bottom of フォロワー
		* 1ユーザーにユーザーがIDが同様のフォロワーは二人以上存在しない
		* 自分を自分がフォローはできない
	end note

	note right of ユーザー
		* 名前は20文字以内
		* アイコンはなくても良い
		* メールアドレスは重複不可
	end note

	note bottom of プロセス
		* プロセスは必ず一つ以上存在する
		* 画像はなくてもよい
	end note

	note bottom of 材料
		* 材料は必ず一つ以上存在する
	end note

	ユーザー "1" --> "0..n" フォロワー
	ユーザー "1" --> "0..n" 投稿
	投稿 "1" --> "0..n" いいね
	投稿 "1" --> "1..n" 材料
	投稿 "1" --> "1..n" プロセス
@enduml
